### ISSUE TITLE
Editing of edge between chemical and activity not working properly

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua-visual-pathway-editor#10]
Two different problems, but they might have the same underlying cause so this should be one ticket. I refer to this example: http://bioghost2.usc.edu:4205/workbench/visual-pathway-editor/?model_id=gomodel%3A61f34dd300000973

1.	I am unable to edit an is-input edge between a chemical and activity. It seems to be specific only to is-input, and not other edge types.

If I click on the is-input edge between benzene and WNT1, the edit box incorrectly shows that it is an is-small-molecule-activator edge, but there’s no way to get the relationship to change. Also, if I press delete, the tool tells me it has deleted the edge but the delete doesn’t happen.
 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/4782928/156564160-49cdad8f-8854-48ba-b27e-31d552367f2e.png">

2.	If I make an is-small-molecule-activator edge, and try to change it to an is-input edge by clicking on “substrate”, it says it has changed but it adds an is-input edge WITHOUT DELETING the is-small-molecule-activator edge, so there are two edges. In the example, I got this result for L-tyrosine to WNT by first connecting them with is-small-molecule-activator, and then trying to edit to is-input.
<img width="206" alt="image" src="https://user-images.githubusercontent.com/4782928/156564190-f87f2d89-94e8-4ee5-ad68-7047347fecec.png">

**Comment by tmushayahama** [comment]
@pgaudet @thomaspd this should be working now on bioghost dev server. 

Also test editing for other edges as well, deleting as this may have affected.

**Comment by pgaudet** [comment]
Looks fixed, thanks!
