### ISSUE TITLE
Pathway too big, doesn't fit in Visual Pathway Editor edit space? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua-visual-pathway-editor#14]
Hi @tmushayahama 

This model: 
http://bioghost2.usc.edu:4205/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A61f34dd300001044

doesnt seem to fit in the window? when I scroll right I get to a point where there seems to be more activity units but I cannot reach them 

<img width="595" alt="image" src="https://user-images.githubusercontent.com/4782928/161102166-d5f82fd4-d460-4163-aaed-ce52deb48cef.png">

Thanks, Pascale

**Comment by tmushayahama** [comment]
Thanks @pgaudet I was forgetting about large models, lemme add variable height. initially I had put a temporary cap of 4000px X 4000px canvas tag  @thomaspd

**Comment by pgaudet** [comment]
I dont think there should ever be a limit? 

We can have a default size so that boxes are zoomed in correctly, but if models dont have maximal sizes, the display cannot have a limit? 


Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @tmushayahama 

This may be unrelated, since I think you only made changes to the layout in bighost, but in http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A60ad85f700001873
the model starts below the initially visible part of the page. Can this be fixed? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Now looks good

**Comment by tmushayahama** [comment]
@pgaudet @thomaspd  just to keep this as a note for future, extremely big models (so far no such huge model) might be cut bcz so far the height and width are static values (don't grow as the model). Would revisit later so that it can be scalable solution
