### ISSUE TITLE
Change label 'is input' to 'input of' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua-visual-pathway-editor#25]
Please change the label to the official RO label: 

[input of](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002352)

@vanaukenk 
@cmungall 
@thomaspd 

Thanks, Pascale

**Comment by tmushayahama** [comment]
I believe this is now on production

**Comment by pgaudet** [comment]
Thanks!
