### ISSUE TITLE
How do you go back to the Noctua landing page from the Visual Editor? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua-visual-pathway-editor#27]
I cannot find the Noctua icon we have on other pages. 

Thanks, Pascale

**Comment by tmushayahama** [comment]
Click on the **Noctua** Text

![image](https://user-images.githubusercontent.com/2273929/165222720-32fc6488-64e5-48a4-8662-16877c564c26.png)

And

Visual Path Editor link refreshes the page

We might want to add shortcuts too, like creating new models from the VPE

@pgaudet

**Comment by pgaudet** [comment]
It would be nice if all workbenches had the same navigation menus

**Comment by tmushayahama** [comment]
The new ones have same navigation Noctua Form, Alliance Pathway, VPE, landing page. Only the graph editor
