### ISSUE TITLE
Creating new model VPE on landing page 

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-visual-pathway-editor#28]
Add a way to create new model VPE on landing page 

Maybe 
![image](https://user-images.githubusercontent.com/2273929/165428653-bdf85b24-d8a2-43f0-aca2-c75055229f20.png)

tagging @pgaudet @thomaspd 
@vanaukenk this can be a landing page issue

**Comment by pgaudet** [comment]
It's on dev

**Comment by tmushayahama** [comment]
@pgaudet it is now on production

**Comment by pgaudet** [comment]
Great!! 

Just wondering, for clarity, is this the Pathway Editor or the Visual Pathway Editor? I realize it takes more space - we could do something like this to remove repeated text: 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/4782928/179677732-00aac0ef-b7aa-4218-9a5a-4c1ec5545975.png">


Thanks, Pascale


@vanaukenk

**Comment by pgaudet** [comment]
@tmushayahama can you have a look at this one?

**Comment by pgaudet** [comment]
@tmushayahama ping

**Comment by vanaukenk** [comment]
@pgaudet @tmushayahama 

I like the idea of having a more general heading above the three links to create models and then a separate heading above review. How about just 'Create' and 'Review' or 'Create Models' and 'Review Models'?

I also like the symmetry of 'Form Editor', 'Pathway Editor', and 'Graph Editor', but if we definitely need the 'visual', let's add it.

**Comment by pgaudet** [comment]
We can keep it simple to ''Create' and 'Review' ' 

and with Form Editor', 'Pathway Editor', and 'Graph Editor', -> we just need to be sure this is updated everywhere. I'll chek the documentation; @tmushayahama can you also check the Noctua tools?

**Comment by tmushayahama** [comment]
@pgaudet @vanaukenk I am working on this one. To clarify, it will be "pathway editor"

**Comment by pgaudet** [comment]
Looks great !

**Comment by vanaukenk** [comment]
Yes, looks good!

**Comment by pgaudet** [comment]
@tmushayahama 

Another thing, we should call the Pathway editor the same way everywhere. Is it possible to update this form the Workbenches menu in the graph editor? 

<img width="245" alt="image" src="https://user-images.githubusercontent.com/4782928/193888731-6abd15ce-6d62-4765-bdaf-c2cbd75b7576.png">


Are there other references to 'Visual Pathway Editor' in the UI? 

Thanks, Pascale

**Comment by tmushayahama** [comment]
@pgaudet @vanaukenk  you can check it out on landing page. As for reference to the "visual pathway editor" I think it should be a different ticket

**Comment by pgaudet** [comment]
Done - now on prod. 

Thanks !!!
