### ISSUE TITLE
Show 'has input' in Activity Unit boxes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua-visual-pathway-editor#3]
Add one more label on the box, where you show the has_input(s) - (gene products that are inside the unit, not small molecules. we'd like to also see gene products without having to open the box)

**Comment by pgaudet** [comment]
Works, thanks

**Comment by tmushayahama** [comment]
@pgaudet @thomaspd I have realized  some models have many has_inputs, has_parts which can make the box taller. Should I limit the has_input, has_part to like 4 and say (+ 2 more) on the display?
