### ISSUE TITLE
"during" annotations are not visible in the visual pathway editor

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua-visual-pathway-editor#32]
All of my annotations will have "during". This is important because the pathway I am curating affects it's target/process  differently at different phases.

**Comment by pgaudet** [comment]
@thomaspd @tmushayahama Can this relation be added in the NVE? And in the 'Detailed view'.

Thanks, Pascale

**Comment by tmushayahama** [comment]
@pgaudet @ValWood @pgaudet you mean ("happens during" Biological Phase)? or there is a new relation called "during" if former, I think its a bug on my side, lemme check it out and fix that. Do you know if something changed in NEO or RO. It disappeared somehow without being touched :) .

Thanks for the ticket @ValWood

**Comment by ValWood** [comment]
I think happens_during is the relation we are using. But I got a bit mixed up with what the relationship set is now. @vanaukenk  could you point me to the current list (sorry I know have asked this multiple times!).
Any way we can change it if we used the wrong thing, just need it to be available for  most of our models.

**Comment by pgaudet** [comment]
Indeed it's 'happens_during' ([RO:0002092](http://purl.obolibrary.org/obo/RO_0002092))

**Comment by vanaukenk** [comment]
Here is the wiki page with the Annotation Relations:
https://wiki.geneontology.org/Annotation_Relations

**Comment by ValWood** [comment]
It was the annotation extension relations I was interested in.
Is this in date?
https://wiki.geneontology.org/index.php/Annotation_usage_examples_for_each_annotation_extension_relation
It seem to include things that we don't use (I needed  it so that we can model extensions so that they can be queried in Intermine,  I wanted to know the current range so that it would work for everyone - we need to separate out the different extension types   because some have genes and some have ontology terms)

**Comment by pgaudet** [comment]
@ccasals reported something similar, see model 62900b6400002447

Happens during can be used in the NVE form, but it's not shown either in the visual editor, nor when you reopen the form. However toggling to the Graph editor, you see the happens during extension. 

Seems to be a display issue. 

Thanks, Pascale

**Comment by tmushayahama** [comment]
now fixed on production. Only happens during **GO Biological Phase GO:0044848**. Next step is to add happens_during **or GO Biological Phase or UBERON:0000105** 
tagging @vanaukenk for better explanation

**Comment by pgaudet** [comment]
Thanks!

**Comment by pgaudet** [comment]
@vanaukenk Can this be closed? @ccasals says this is working for her

**Comment by ccasals** [comment]
I believe you have the wrong ccasals but I presume my alter ego does in fact find whatever this is to be working :)

**Comment by vanaukenk** [comment]
@pgaudet - I think this is really up to the VPE product owner (who, I believe, is @thomaspd)

**Comment by pgaudet** [comment]
Now working for children of Uberon life stages. Awesome!
