### ISSUE TITLE
Noctua slow and bugging this afternoon

### ISSUE THREAD

**Issue by ccasalsc** [geneontology/noctua-visual-pathway-editor#47]
Hi, 
I am correcting some of my models and I had many issues to do it...
- First of all, the program was sending a message that I wasn't logged even if I was... refreshing the page solved the problem but I had it with each model.
- Second, I wanted to change the type of evidence and/or add a PMID or 'with' but after doing the changes these weren't take in account and the old annotations were still there, again, reloading the page solved the problem... also for the 4 models I have corrected...
- Third, when I went back to the main Noctua page, none of the models where saved even if I did the modifications in the 'visual pathway editor'. I had, for each of them, to go to the graphical editor and save them.

Apparently Sylvain is not having the same issues than me, so I don't know if this can be related to the navigator we are using (I am on Firefox) or something else.
I hope you will be able to solve these bugs!! :)
Thank you

**Comment by vanaukenk** [comment]
Following up with @ccasalsc , it looks like these issues aren't reproducible.

We'll close the ticket for now, but if the same issues come up again, we will try to screen share right away to understand better what might be happening.
