### ISSUE TITLE
New causal relations decision tree for additional MF-MF relations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-visual-pathway-editor#48]
@tmushayahama @ukemi @pgaudet @thomaspd 

I've put together a [slide deck](https://docs.google.com/presentation/d/1ODFtV2aEeUeOUDs8dupre-3hUJchLFMMu-kChPKR1Oc) for implementing the new causal relations decision tree on the VPE.

The slides step through each of the relations and show the values that a curator would need to select to get that relation.

Tremayne, I put each step on a separate slide for simplicity, the but decision tree pop-up would look the same way that you have it now, i.e. all of the decisions will be in the same pop-up window with some only available depending on what initial relationship the curator chooses.

I'm happy to review the slides this week to make sure everything is clear and correct.

Thx.

**Comment by vanaukenk** [comment]
@tmushayahama 
Is there anything more we need to do before putting the new decision tree on noctua-dev for curators to test?

**Comment by tmushayahama** [comment]
@vanaukenk I have made a PR https://github.com/geneontology/noctua-visual-pathway-editor/pull/49 . Only one relationship is missing indirectly positively regulates (RO:00002407)

tagging @kltm it is not appearing on graph editor nor on the list on known_relations

**Comment by vanaukenk** [comment]
Noting here that I checked for the indirectly positively regulates (RO:0002407) label in the pop-up decision tree window on noctua-dev after we cycled this evening and it's still not there, i.e. the pop-up window still just displays the term id.

We'll have to do some more sleuthing to figure out why it's not displaying.

@kltm @tmushayahama

**Comment by kltm** [comment]
Okay, looking at what's coming over the wire, it seems that there is no `property-label` for RO:0002407. @balhoff Does this look alright in the ontology? Is it possible that this didn't propagate properly when we did the restart?

**Comment by vanaukenk** [comment]
I think we can go ahead and move the new causal relations decision tree on the VPE to production.
I'll leave this ticket open, though, so we can sort out what's happening with the label for RO:0002407.

**Comment by kltm** [comment]
We've tracked it to a typo somewhere: too many '0's.
Will grep through and fix.

**Comment by vanaukenk** [comment]
Added to production pathway editor on 2023-01-26
