### ISSUE TITLE
Link to 'annotation preview' from visual editor

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua-visual-pathway-editor#55]
Hi @tmushayahama 

Is it possible to add a link to view the Annotation Preview from the visual editor? (not sure why it's no there). The GPAD export is not easily readable. 

Thanks, Pascale

**Comment by vanaukenk** [comment]
@pgaudet @tmushayahama 

A link to the Annotation Preview is available from the Workbenches menu on the upper right of the pathway editor.
Does that work for curators?

Step 1:
![image](https://user-images.githubusercontent.com/1730534/215794455-70389156-611e-42a9-aa9c-969275ac4b1f.png)


Step 2:
![image](https://user-images.githubusercontent.com/1730534/215794720-0bf3a2f1-3f76-4413-9c2b-be8922a51ebc.png)

**Comment by pgaudet** [comment]
Yes that works! thanks, Pascale
