### ISSUE TITLE
Create new chemical should not allow PRO IDs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua-visual-pathway-editor#73]
Hello, 

In the Pathway Editor, when creating a chemical, all PRO IDs are  available, see screenshot: 

<img width="712" alt="image" src="https://github.com/geneontology/noctua-visual-pathway-editor/assets/4782928/47f0b455-85fc-4502-a276-5f753efc3951">

Could PRO IDs be excluded from the auto-fill? Since these are. not allowed as chemicals? 

Thanks, Pascale

**Comment by tmushayahama** [comment]
PRO ids should be classed as information biomacromolecules in NEO
tagging  @balhoff @pgaudet @kltm @thomaspd

**Comment by balhoff** [comment]
@tmushayahama I checked `PR:000045358`, and it is classified under 'information biomacromolecule' in go-lego. Are you getting a response from Minerva that doesn't have this root type for this term?

**Comment by pgaudet** [comment]
> PRO ids should be classed as information biomacromolecules 

Are 'information biomacromolecules' excluded from chemicals?

**Comment by tmushayahama** [comment]
@pgaudet Actually I am surprised, the definition is "isa_closure Chemical (CHEBI:24431), so it means all the information biomacromolecules are present

**Comment by pgaudet** [comment]
yes, if you could exclude the information biomacromolecule branch of ChEBI, I think that would work (at least the idea seems correct).
