### ISSUE TITLE
Search annotation is not functionning properly...Loss of evidence codes

### ISSUE THREAD

**Issue by pmasson55** [geneontology/noctua-visual-pathway-editor#75]
Hi,

It seems that all evidence codes have disappeared from the search annotation tool (at least for some people). References are still present as well as the assigned by field. But for the evidences, it' all gone...
Hope it's easily fixed.
Thx in advance,
Patrick.

**Comment by vanaukenk** [comment]
@pmasson55   Thank you for reporting this.

I can confirm that the evidence codes are missing from the search annotation functionality on both the Noctua VPE and the Noctua form.

I also just checked the Function Companion on the graph editor and although the evidence codes are displayed in the AmiGO-like interface that comes up, when I try to filter by Evidence Code on the left-hand list of facets, it says 'Nothing to filter'.  The same behavior is found on the main GO AmiGO site.

This suggests to me that there might be an issue with evidence codes in the underlying annotation index, but I'll need @kltm to investigate further.

@tmushayahama is out this week, but I'm not sure this is a strictly Noctua bug.

We'll try to get this sorted ASAP.

**Comment by kltm** [comment]
Working on it at https://github.com/geneontology/amigo/issues/717
