### ISSUE TITLE
Cannot change a development model to production

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua-visual-pathway-editor#80]
I suspect this is because I have no evidences on my inputs and outputs, but I don't understand why these need evidence, this is what the reaction does? (I only added them when the reaction has multiple specificities), but I don't have a specific evidence to use. I could find one but it feels like busy work...

**Comment by vanaukenk** [comment]
Instruction for how to update a model's state are in the [Basic Workflow](https://docs.google.com/document/d/1RNbr-2T6CSZfaYKDrom7259IK6ck82vZLThgymyNZ28/edit#heading=h.cfjyki8acsb3) section of the VPE users manual.

@ValWood Let us know if this is clear enough or we should add more screenshots/directions.
